env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - '@react-native-community'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  "quotes": ['off', "single", { "avoidEscape": true }],
  'prettier/prettier': 0,
  'react-native/no-inline-styles': 'off',
  'react-hooks/rules-of-hooks': 'off',
  'react-hooks/exhaustive-deps': 'off',
}
