// module.exports = [
//   "Plumber",
//   "Electrician",
//   "Carpenter",
//   "Car Detailing",
//   "Masonry (Brick, Concrete)",
//   "Auto Mechanic (Foreign, Domestic, Diesel)",
//   "HVAC Technician",
//   "Lawn care",
//   "IT Tech Support",
//   "Tow Truck and Roadside Assistance Services",
//   // "Random (w/ disclaimer)",
//   "Event Planner",
//   "Caterers",
//   "Hot Shot Delivery and Courier Services",
//   "Shipping Pallets, Containers and Custom Crate Builders",
//   "Web Designer",
//   "Healthcare professionals (PA Nursing NP/RN/LPN, MA, CNA, Phlebotomy, Specimen Collector, Paramedical Examiner, Covid-Testing)",
//   "Snow and Ice Removal",
//   "Demolition",
//   "Debris Removal",
//   "Tree Services",
//   "Roof Repair",
//   "Dump Truck Services",
//   "Alarm Systems/Cameras and Networking Installation",
//   "Cable/Satellite Installation",
//   "Janitorial/Maid/Cleaning Services",
//   "Veterinarian Services",
//   "Animal Grooming",
//   "Baby Sitters/Nanny",
//   "Garage Door and Garage Door Opener Installation/Repair",
//   "Painter/Finish",
//   "HVAC (Heating Ventilation and Air Conditioning)",
//   "Engineering",
//   "Engineering",
//   "Computer Repair",
//   "Event Planner (Catering DJ, Party/Concert Promoter)",
//   "Modeling/Acting",
//   "Flooring (Tile, Wood, Laminate, Carpet)",
//   "Carpet Cleaning",
//   "Window/Door Installation/Repair (Glass, Screens)",
//   "Window Blinds, Shades, Drapes, Curtains and Shutters",
//   "Seamstress/Tailor",
//   "Beautician (Natural and Chemically Treated Hair, Braiding,",
// ].sort();

module.exports = [
  "Plumber",
  "Electrician",
  "Carpenter",
  "Car Detailing",
  "Masonry (Brick, Concrete)",
  "Auto Mechanic",
  "Lawn care",
  "IT Tech Support",
  "Tow Truck and Roadside Assistance",
  "Event Planner",
  "Caterers",
  "Hot Shot Delivery & Courier Services",
  "Shipping Pallets, Containers and Custom Crate Builders",
  "Web Designer",
  "Healthcare professionals",
  "Snow and Ice Removal",
  "Demolition",
  "Debris Removal",
  "Tree Services",
  "Roof Repair",
  "Dump Truck Services",
  "Alarm Systems/Cameras",
  "Networking Installation",
  "Cable/Satellite Installation",
  "Janitorial/Maid/Cleaning Services",
  "Veterinarian Services",
  "Animal Grooming",
  "Baby Sitters/Nanny",
  "Garage Door Installation/Repair",
  "Painter/Finish",
  "HVAC (Heating & Air Conditioning)",
  "Engineering",
  "Computer Repair",
  "Modeling/Acting",
  "Flooring",
  "Carpet Cleaning",
  "Window Blinds, Shades, Drapes, Curtains and Shutters",
  "Seamstress/Tailor",
  "Beautician",
  "Random (No Skill Required)",
].sort();
