module.exports = [
  "Plumber",
  "Electrician",
  "Carpenter",
  "Masonry (Brick, Concrete)",
  "Auto Mechanic (Foreign, Domestic, Diesel)",
  "HVAC Technician",
  "Lawn care",
  "IT Tech Support",
  "Tow services",
  "Random (w/ disclaimer)",
  "Maid services",
  "Janitorial",
  "Event Planner",
  "Caterers",
].sort();
