module.exports = [
  "Air conditioner installation",
  "Appraising of property",
  "Barbecue pit maintenance",
  "Cabinet refacing",
  "Carpentry",
  "Ceiling repair",
  "Ceramic tile repair",
  "Cleaning",
  "Concrete work",
  "Countertops",
  "Curtain hanging",
  "Decks",
  "Door installation",
  "Door repair",
  "Drain cleaning",
  "Dryer repair",
  "Dryer vent cleaning",
  "Dryer vent installation",
  "Drywall Installation",
  "Drywall repair",
  "Electrical wiring",
  "Energy Updates",
  "Fan installation",
  "Fence fixing",
  "Fireplace cleaning",
  "Flooring Installation and Repair",
  "Foundations",
  "Framing",
  "Garage door openers",
  "Garage doors",
  "General Maintenance",
  "Gutter Cleaning",
  "Gutter Repair",
  "Heating system tune-up",
  "Home inspections",
  "Home security systems",
  "Hot tubs and spas",
  "Insulation installation (batts)",
  "Insulation installation (blown-in)",
  "Lamp repairs",
  "Landscaping",
  "Lawncare",
  "Lockset adjustment",
  "Molding installation",
  "Moving",
  "Paint removal",
  "Painting",
  "Patio stone installation",
  "Pest control",
  "Photography",
  "Plumbing repairs",
  "Porches",
  "Remodeling basements",
  "Remodeling bathrooms",
  "Remodeling kitchens",
  "Safety modifications",
  "Sealing driveways",
  "Senior Living Modifications",
  "Septic system repair",
  "Shelf installation",
  "Shelving",
  "Skylight installation",
  "Solar panels",
  "Soundproofing",
  "Sprinkler repair",
  "Sprinkler system installation",
  "Stain removal",
  "Staining furniture",
  "Stone work",
  "Storage area construction",
  "Storage area repair",
  "Swapping a toilet",
  "Swimming pool maintenance",
  "Tiling",
  "Wall building",
  "Waste and junk removal",
  "Water purification",
  "Water softening",
  "Window cleaning",
  "Window installation",
  "Window repair",
];
